//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taskss
    {
        public Taskss(int taskID, int? userID, string dueDate, bool completion, string taskDescription)
        {
            TaskID = taskID;
            UserID = userID;
            DueDate = dueDate;
            Completion = completion;
            TaskDescription = taskDescription;
        }
        public Taskss()
        {
            TaskID = 0;
            UserID = 0;
            DueDate = "";
            Completion = false;
            TaskDescription = "";
        }

        public int TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string DueDate { get; set; }
        public bool Completion { get; set; }
        public string TaskDescription { get; set; }
    }
}
