//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User(int userID, string email, string password)
        {
            UserID = userID;
            Email = email;
            Password = password;
        }
        public User()
        {
            UserID = 0;
            Email = "";
            Password = "";
        }

        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
